# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            IPFS Tutorials
tagline:          'Learn how to use the Decentralized Web'
description:      'Tutorials on IPFS and its related technologies.'
url:              http://flyingzumwalt.github.io/ipfs-tutorials/
baseurl:          /ipfs-tutorials

author:
  name:           'Matt Zumwalt'
  url:            https://twitter.com/flyingzumwalt

# Custom vars
version:          0.0.1
gems:             [jekyll-paginate, jekyll-gist]

github:
  repo:           https://github.com/flyingzumwalt/ipfs-tutorials
